apiVersion: v1
kind: Service
metadata:
  name: new-api
  namespace: new-api
  labels:
    app: new-api
    component: new-api
spec:
  type: NodePort
  selector:
    app: new-api
    component: new-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30300
      protocol: TCP
      name: http
