---
apiVersion: v1
kind: Secret
metadata:
  name: new-api-secret
  namespace: {{ .Values.namespace.name }}
  labels:
    app: new-api
type: Opaque
stringData:
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword | quote }}
  SQL_DSN: {{ .Values.secrets.sqlDsn | quote }}
  REDIS_CONN_STRING: {{ .Values.secrets.redisConnString | quote }}
